### ISSUE TITLE
Failed to setup Add-on

### ISSUE THREAD

**Issue by Puntoboy** [mmillmor/geo_home#25]
I recently upgraded to 2023.6.2 and since then the integration has stopped working. This is the error from the logs.

Logger: homeassistant.config_entries
Source: custom_components/geo_home/__init__.py:19
Integration: Geo Home
First occurred: 14:26:18 (2 occurrences)
Last logged: 14:35:42

Error setting up entry Geo Home for geo_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/geo_home/__init__.py", line 19, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by mmillmor** [comment]
That code was replaced in February (https://github.com/mmillmor/geo_home/commit/c7a160141095ba06903e2d2c1deebcd89f723944). If you upgrade to the latest version of the geo_home integration (version 1.8), your error will go away

**Comment by Puntoboy** [comment]
I have this version?

![image](https://github.com/mmillmor/geo_home/assets/11718878/9dd0fcc2-746e-418d-8dfe-0500b4119ed6)

**Comment by mmillmor** [comment]
Definitely not the right version (although I don't know what version that is). I'm not sure if you even have the right repository there given the number of stars and issues it shows. Are you using HACS? Did you point it at https://github.com/mmillmor/geo_home? It should offer you an update to the latest version if you are.

**Comment by Puntoboy** [comment]
Hmmm, I didn't have that one I think, but just added a new one. I installed this over a year ago and had no prompt to update through HACS. Just rebooting.

**Comment by Puntoboy** [comment]
That's better, it's working again now. thank you.

**Comment by mmillmor** [comment]
That's great. You should have some new sensors on there compared to the old version (e.g, standing charge, cost per day/week/month), so hopefully a useful upgrade overall
