### ISSUE TITLE
Not Prompted for Username/Password

### ISSUE THREAD

**Issue by mark3267** [mmillmor/geo_home#3]
After installing through HACS I can see the integration is listed 

![image](https://user-images.githubusercontent.com/47664681/203322283-6037e3ac-7497-4f2b-80bc-d5852518e601.png)

but when I click it only displays the readme rather than opening the config page to enter email/password

![Capture](https://user-images.githubusercontent.com/47664681/203322072-e073ebc8-a3d5-4517-9f1a-18a67b6007ee.PNG)

**Comment by berry120** [comment]
Same issue here, unless I'm missing something obvious!

**Comment by berry120** [comment]
@mark3267 In my case I missed a step - go to Settings -> Devices & services -> Add integration, then find "GeoHome" in the list. That will then prompt you for the username / password.

**Comment by mark3267** [comment]
> @mark3267 In my case I missed a step - go to Settings -> Devices & services -> Add integration, then find "GeoHome" in the list. That will then prompt you for the username / password.

Perfect!!! All working now. Thanks
