### ISSUE TITLE
Update didn't fix the issue

### ISSUE THREAD

**Issue by iendicott** [mmillmor/geo_home#31]
Hi removed the repo from HACS rebooted and  re-added, after adding the integration, still the same. Sorry

_Originally posted by @iendicott in https://github.com/mmillmor/geo_home/issues/29#issuecomment-1663046275_

**Comment by iendicott** [comment]
I've just rolled back to the version from 1st April 2023 and this works with no issues.

**Comment by mmillmor** [comment]
I have reverted to the old code

**Comment by iendicott** [comment]
Thanks all working straight out the box now. Happy to help to fault find if you need me too?
