### ISSUE TITLE
Sensor.Gas units

### ISSUE THREAD

**Issue by aaronchidgey** [mmillmor/geo_home#34]
What unit does Sensor.Gas measure in?

When I add it to the energy dashboard its seems to recording a number a lot higher than what I'm using. Today I've used roughly 5 kWh but the dashboard is showing 57
![image](https://github.com/mmillmor/geo_home/assets/146442723/b64329bc-7446-40c5-8ffe-5098409cdf4e)
![image](https://github.com/mmillmor/geo_home/assets/146442723/1766a1a8-c96c-4f55-a716-c0d46dfccee4)

I wondered if it was Wh however if I change the unit of measurement it still shows in kWh in the dashboard. I could however be doing something wrong.
![image](https://github.com/mmillmor/geo_home/assets/146442723/3d43470b-bc08-4802-a1ef-c2a7b4380a6d)

**Comment by mmillmor** [comment]
The system should be measuring in kWh, but perhaps geohome are sending a different unit for your system. Have you looked in the geohome app to see what this might correspond to?
