### ISSUE TITLE
FR: Support for the Dutch Geo trio 2 p1 meter

### ISSUE THREAD

**Issue by erkr** [mmillmor/geo_home#36]
Hi 
Thanks for offering this custom geo integration.  The dutch geo P1 meter (model trio 2) is not supported by their geo app. So there is no way to create a cloud account. 
Both the P1 meter and display are connected with each other via the local WiFi.  
Don’t know if it is possible to gather data from P1 meter locally. If so, support for this Geo model would be great. Otherwise it would have saved me time if it was mentioned in the readme that this model is not supported 👍
Best Eric

**Comment by mmillmor** [comment]
Eric, I'm afraid I don't have one of those meters, so I don't have any way to build or test that. Do you have any documentation though?

**Comment by erkr** [comment]
No I don't have any documentation.   What I can try, is to find out if there is some web api on these devices and provide data on the response payloads. Presuming the interface is not be totally different from the other geo trio models, do you have a head start for me where to begin?!
Best Eric

**Comment by mmillmor** [comment]
If you have documented apis, I could help you produce an integration that uses it. But without documentation, there's nothing I can do

**Comment by erkr** [comment]
Clear, I will try to connect to the p1 device to find out if there is some kind of REST api.

**Comment by erkr** [comment]
I contacted the Dutch reseller and according then the wifi for the dutch Geo trio 2 p1 displays  is only used for firmware updates. So not possible to read data locally.
Very disappointing but that blocks  this FR. Will close it. Thanks for your time
