### ISSUE TITLE
Geo Home Meter not displaying data

### ISSUE THREAD

**Issue by iendicott** [mmillmor/geo_home#40]
Registered the app on my phone and I can see the meter on my network.
Added the Geo Home Repo via HACS and installed.
Added the Add-on in the Integration.

I receive a prompt to login with a Username and Password
Tried the login I used on the my registered account that allowed me to login and I can see 34 entities but none of them showing data.
Tried a login that I know doesn't work again I can see 34 entities but none of them showing data.

I am sure before you had to enter in the IP address of the meter you have on your network but this is not appearing.

![1](https://github.com/mmillmor/geo_home/assets/73525618/ad7233ac-5a8c-4c24-ba65-8c6cd53ff35c)
![2](https://github.com/mmillmor/geo_home/assets/73525618/b50a8115-cf09-4cd3-b04a-26c03d4e0753)
![3](https://github.com/mmillmor/geo_home/assets/73525618/ac56d9f9-d969-4d38-a52a-8ffe147972ee)
![4](https://github.com/mmillmor/geo_home/assets/73525618/92dfdb5c-5835-4674-93ff-02f0bfd5548e)
![5](https://github.com/mmillmor/geo_home/assets/73525618/c46da118-e610-42a6-aaad-cfef9e00c373)
![6](https://github.com/mmillmor/geo_home/assets/73525618/53f809fa-c8c1-4bf6-983c-4f5ec8269d33)

![Mobile App](https://github.com/mmillmor/geo_home/assets/73525618/35cf2339-733f-400f-8e05-49a58b881a6a)

**Comment by mmillmor** [comment]
Do you see any errors in the logs @iendicott ?

**Comment by iendicott** [comment]
Hi @mmillmor are you refering to the Logs in the Home Assistant Logbook or another location? Please let me know If another location where I can find these and I will add them into this issue.

**Comment by mmillmor** [comment]
@iendicott , I mean in the home assistant logbook. If there are fatal errors, they should show there

**Comment by iendicott** [comment]
@mmillmor So I think I know what is happening.
I used to have another GeoHome device and I think it is looking for that. I enabled debugging on HA and can see this

> 2024-04-04 14:54:07.321 WARNING (SyncWorker_6) [custom_components.geo_home.geohome] GeoHome Device Details API returned 401
> 2024-04-04 14:55:36.704 ERROR (MainThread) [homeassistant.components.fully_kiosk] Timeout fetching 192.168.1.173 data
> 2024-04-04 14:56:07.190 WARNING (SyncWorker_5) [custom_components.geo_home.geohome] GeoHome Auth API returned : 401

Problem is the new device is on a different IP.
Is there a way to clear this out? I have removed the Add-on and the HACS plugin and rebooted but it's still coming up with that error.

**Comment by iendicott** [comment]
And as if by magic it's started working again. 👍

**Comment by iendicott** [comment]
And as if by magic it's started working again. 👍
