### ISSUE TITLE
Multiple system IDs

### ISSUE THREAD

**Issue by dunxd** [mmillmor/geo_home#9]
After my Trio stopped talking to the gas meter, I reset it.  This has resulted in a different system ID being generated - the API response to https://api.geotogether.com/api/userapi/v2/user/detail-systems?systemDetails=true now returns two.  The new one is the second one returned.

If I use the REST method I used previously, I can get the data ok.  I suspect that this integration is using the old/first system returned and so all the entities are empty.

**Comment by dunxd** [comment]
Confirmed by changing index of system_roles in line 103 in geohome.py to 1 rather than 0.

```
self.deviceId = system_roles[1]["systemId"]
```

Now the data is being collected.  I don't see any indication in system_roles which is the current system - perhaps the newest is listed last?

**Comment by dunxd** [comment]
Another thing I noticed while exploring the API responses is that the devices property of the old device in systemDetails is empty, whereas the new one is populated with the TRIO, WIFI_MODULE and JNS169_ZIGBEE.

**Comment by mmillmor** [comment]
@dunxd, can you share a copy of the complete service response (redact any personal information with "REDACTED")

**Comment by dunxd** [comment]
Here is the response to https://api.geotogether.com/api/userapi/v2/user/detail-systems?systemDetails=true

```
{
    "systemRoles": [
        {
            "name": "REDACTED",
            "systemId": "REDACTED (New id)",
            "roles": [
                "READ",
                "WRITE"
            ]
        },
        {
            "name": "REDACTED",
            "systemId": "REDACTED (Old id)",
            "roles": [
                "READ",
                "WRITE"
            ]
        }
    ],
    "systemDetails": [
        {
            "name": "REDACTED",
            "devices": [
                {
                    "deviceType": "TRIO_II_TB_GEO",
                    "sensorType": 94,
                    "nodeId": 0,
                    "versionNumber": {
                        "major": 5,
                        "minor": 9
                    },
                    "pairedTimestamp": 0,
                    "pairingCode": "CCCCCC",
                    "upgradeRequired": false
                },
                {
                    "deviceType": "WIFI_MODULE",
                    "sensorType": 81,
                    "nodeId": 64,
                    "versionNumber": {
                        "major": 2,
                        "minor": 6
                    },
                    "pairedTimestamp": 0,
                    "pairingCode": "EEEEEE",
                    "upgradeRequired": false
                },
                {
                    "deviceType": "JN5169_ZIGBEE",
                    "sensorType": 96,
                    "nodeId": 65,
                    "versionNumber": {
                        "major": 139,
                        "minor": 142
                    },
                    "pairedTimestamp": 0,
                    "pairingCode": "DDDDDD",
                    "upgradeRequired": false
                }
            ],
            "systemId": "REDACTED (New id)"
        },
        {
            "name": "REDACTED",
            "devices": [],
            "systemId": "REDACTED (Old id)"
        }
    ]
}
```

I noticed that the order is different today, which would explain why I am seeing gaps in my data using the index to select the second item from systemRoles. The order may be random, so it is probably necessary to select the systemid from the objects in systemDetails where devices is populated.

**Comment by dunxd** [comment]
Yes - the order has switched around again when I checked with Postman just now - minutes after I updated geohome.py to pick the first returned.

**Comment by mmillmor** [comment]
Please give the updated version a try. It works for me with a single system and I suspect it will work for you, but there may be other gotchas

**Comment by dunxd** [comment]
It seems to be working, although the HA Energy dashboard is so pernickety nothing is yet showing up in there since I made the change. But I am seeing current values for the sensor.electricity entity in Developer Tools.
